// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinw4tywd2uLXxPzXxVqLKRmRIWysCr1E',
    appId: '1:784875649035:web:4dafe74a476eba5eb9af0e',
    messagingSenderId: '784875649035',
    projectId: 'noteauth-2a72b',
    authDomain: 'noteauth-2a72b.firebaseapp.com',
    storageBucket: 'noteauth-2a72b.appspot.com',
    measurementId: 'G-BHQ54YHWB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqv8Eq8e6X8gRJMmkbbOgJLLDFiVmPBcA',
    appId: '1:784875649035:android:42e1fcb66d5a0ee6b9af0e',
    messagingSenderId: '784875649035',
    projectId: 'noteauth-2a72b',
    storageBucket: 'noteauth-2a72b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPu4R9xcGlSPhr4cUIBnRmBntaf4cV5x8',
    appId: '1:784875649035:ios:e1558519d5228139b9af0e',
    messagingSenderId: '784875649035',
    projectId: 'noteauth-2a72b',
    storageBucket: 'noteauth-2a72b.appspot.com',
    iosBundleId: 'com.example.loginNoteFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPu4R9xcGlSPhr4cUIBnRmBntaf4cV5x8',
    appId: '1:784875649035:ios:2715bd0c2de24224b9af0e',
    messagingSenderId: '784875649035',
    projectId: 'noteauth-2a72b',
    storageBucket: 'noteauth-2a72b.appspot.com',
    iosBundleId: 'com.example.loginNoteFb.RunnerTests',
  );
}
